# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: gojo

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  iamRoleStatements:
     - Effect: Allow
       Action:
         - dynamodb:DescribeTable
         - dynamodb:Query
         - dynamodb:Scan
         - dynamodb:GetItem
         - dynamodb:PutItem
         - dynamodb:UpdateItem
         - dynamodb:DeleteItem
       Resource:
         - 'Fn::Join':
           - ":"
           -
             - "arn:aws:dynamodb"
             - Ref: 'AWS::Region'
             - Ref: 'AWS::AccountId'
             - table/${self:custom.entriesTableName}

custom:
  entriesTableName: gojo-entries-${opt:stage, self:provider.stage}
package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  web:
    handler: bin/web
    events:
        - http:
            path: create
            method: post
        - http:
            path: get/{id}
            method: get
        - http:
            path: home
            method: get
        - http:
            path: public/{asset}
            method: get
    environment:
        STAGE: ${opt:stage, self:provider.stage}
        TABLE_NAME: ${self:custom.entriesTableName}

resources:  # CloudFormation template syntax
  Resources:
    entriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.entriesTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        SSESpecification:
          SSEEnabled: true
plugins:
    - serverless-dynamodb-local
    - serverless-offline

